image: mcr.microsoft.com/dotnet/sdk:5.0

tasks:
  - name: DOTNET
  - init: |
          cp -r /usr/share/dotnet /workspace
    command: /workspace/dotnet/dotnet watch run

vscode:
  extensions:
    - muhammad-sammy.csharp
