image: gitpod/workspace-dotnet

tasks:
  - name: front-end
    init: echo 'starting react backend server'
    command: bash startup.sh

vscode:
  extensions:
    - muhammad-sammy.csharp
    - projektanker.code-butler
    - jsw.csharpextensions
    - fernandoescolar.vscode-solution-explorer
    - TabNine.tabnine-vscode
    - Trelent.trelent
